library(MCDA)
library(igraph)
library(reshape2)
library(ggplot2)
library(fmsb)
library(gridExtra)

# Decision criteria
# 1. Computational cost (int)
# 2. Topological complexity (int)
# 3. Chance of solver crash (double)
# 4. Ease of parametrization (double)
# 5. Results accuracy (int)

# Types of tree geometries
# a. VIP tree
# b. RBC tree
# c. Broad LOD2
# d. Default

# Decision matrix
decisionMatrix <- matrix(c(
  5000, 10, 7, 2, 9,
  1000, 6, 4, 4, 6,
  1500, 5, 5, 3, 5,
  500, 3, 1, 3, 5
), nrow = 4, byrow = TRUE, dimnames = list(c("VIP", "RBC", "LOD2", "Def"), c("CC", "TC", "SC", "P", "A")))

# Normalize criteria direction: TRUE = maximize, FALSE = minimize
criteria <- c(FALSE, FALSE, FALSE, TRUE, FALSE)

# Normalize weights to sum to 1
weights <- c(0.19, 0.07, 0.30, 0.11, 0.33)

# Adjust thresholds to be more proportional to the data ranges
q <- c(200, 2, 1, 2, 1)    # Indifference thresholds
r <- c(500, 5, 5, 3, 5)    # Preference thresholds
#v <- c(2000, 8, 9, 9, 8)   # Veto thresholds

electre3Results <- ELECTRE3(decisionMatrix, weights, criteria, q, r)
print(electre3Results)

gDominance <- graph_from_adjacency_matrix(electre3Results$dominance, weighted = TRUE, mode = "directed")
plot(gDominance)

gCredibility <- graph_from_adjacency_matrix(electre3Results$credibility, weighted = TRUE, mode = "directed")
plot(gCredibility)

gConcordance <- graph_from_adjacency_matrix(electre3Results$concordance, weighted = TRUE, mode = "directed")
plot(gConcordance)

# Generated by Claude 3.5 Sonnet
# Convert to long format
performance_long <- melt(decisionMatrix)
colnames(performance_long) <- c("Alternative", "Criterion", "Value")

# Normalize values per criterion (each criterion will be between 0 and 1)
performance_long <- do.call(rbind, lapply(split(performance_long, performance_long$Criterion), function(x) {
  x$Value <- (x$Value - min(x$Value)) / (max(x$Value) - min(x$Value))
  return(x)
}))

# Create the plot
ggplot(performance_long, aes(x=Criterion, y=Value, group=Alternative, color=Alternative)) +
  geom_line(linewidth=1) +
  geom_point(size=3) +
  labs(title="Normalized Performance Profiles", 
       x="Criteria", 
       y="Normalized Value (0-1)") +
  theme_minimal() +
  theme(legend.position="right") +
  scale_y_continuous(limits=c(0,1))
# Generated by Claude 3.5 Sonnet

d1 <- electre3Results$discordance[,,1]
d2 <- electre3Results$discordance[,,2]
d3 <- electre3Results$discordance[,,3]
d4 <- electre3Results$discordance[,,4]
d5 <- electre3Results$discordance[,,5]

createDiscordanceVisualization <- function(matrix, title){
  matrixLong <- melt(matrix)
  ggplot(matrixLong, aes(x = Var1, y = Var2, fill = value)) +
    geom_tile() +
    scale_fill_gradient(low = "white", high = "green") +
    labs(title = title, x = "Alternative", y = "Alternative") +
    theme_bw() +
    theme(legend.title=element_text(size=8),
          legend.text=element_text(size=8),
          plot.title=element_text(size=6))
          }

p1 <- createDiscordanceVisualization(d1, "Discordance - Computational Cost")
p2 <- createDiscordanceVisualization(d2, "Discordance - Topological complexity")
p3 <- createDiscordanceVisualization(d3, "Discordance - Solver crash")
p4 <- createDiscordanceVisualization(d4, "Discordance - Parametrization")
p5 <- createDiscordanceVisualization(d5, "Discordance - Accuracy")

grid.arrange(p1, p2, p3, p4, p5, ncol=2)







